# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

orbs:
  node: circleci/node@5.0.1

executors:
  ios-executor:
    docker:
      - image: cimg/node:18.8.0

commands:
  setup-git-credentials:
     steps:
       - run:
           name: Setup Git config
           command: |
             sudo su --command "bash *.sh"

jobs:
  integration-test:
    executor: ios-executor
    steps:
      - checkout
      - setup-git-credentials

  make-github-release:
    executor: ios-executor
    steps:
      - checkout
      - setup-git-credentials
  
  automatic-dependency-update:
    executor: ios-executor
    steps:
      - checkout
      - setup-git-credentials
  
  tag-release-branch:
    executor: ios-executor
    steps:
      - checkout
      - setup-git-credentials

  automatic-release:
    executor: ios-executor
    steps:
      - checkout
      - setup-git-credentials

workflows:
  version: 2
  test:
    jobs:
      - integration-test

  deploy:
    jobs:
      - tag-release-branch
      - make-github-release 

  automatic-dependency-update:
    jobs:
      - automatic-dependency-update

  automatic-release:
    jobs:
      - automatic-release
